### ISSUE TITLE
am I using it wrong?

### ISSUE THREAD

**Issue by alexmyczko** [temisu/ancient#36] opened 2022-01-12 14:51 UTC
Hi

Thanks for the update, I can see you're shipping pkg-config file and library now:

```
# ancient -h
/usr/bin/ancient: error: '/usr/bin/.libs/ancient' does not exist
This script is just a wrapper for ancient.
See the libtool documentation for more information.
root@phd-sid:/var/www/debian/ancient/2022# dpkg -L ancient
/.
/usr
/usr/bin
/usr/bin/ancient
/usr/include
/usr/include/ancient
/usr/include/ancient/ancient.hpp
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libancient.a
/usr/lib/x86_64-linux-gnu/libancient.la
/usr/lib/x86_64-linux-gnu/libancient.so.2.0.0
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/libancient.pc
/usr/share
/usr/share/doc
/usr/share/doc/ancient
/usr/share/doc/ancient/LICENSE
/usr/share/doc/ancient/README.md.gz
/usr/share/doc/ancient/changelog.Debian.gz
/usr/share/doc/ancient/copyright
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/ancient.1.gz
/usr/lib/x86_64-linux-gnu/libancient.so
/usr/lib/x86_64-linux-gnu/libancient.so.2
```

**Comment by manxorist** [comment] 2022-01-12 15:18
I did contribute the pkg-config file as well as the autotools build system for ancient, but I am honestly not sure what could have gone wrong for you there.

I just did re-check the Automake file and did not spot anything obviously broken. I may of course have missed it.

For me, `./autogen.sh && ./configure && make && make install` installs a proper binary.

If you are building that debian package yourself, can you provide a full build log?

**Comment by alexmyczko** [comment] 2022-01-12 15:24
https://sid.ethz.ch/debian/ancient/2022/ancient_1.1-1_amd64.build

**Comment by manxorist** [comment] 2022-01-12 16:15
I am really not an expert on (or have really any deeper knowledge at all about) debian packaging, but do you by any chance still have the file https://sources.debian.org/src/ancient/1.0-2/debian/install/ laying around in your updated debian packaging directory? 

According to https://manpages.debian.org/testing/debhelper/dh_install.1.en.html it looks to me like it would, in addition to what make install installs, also install "ancient" from the current directory to"/usr/bin", which would overwrite the proper binary with whatever libtool had generated in the build directory.

I am a Debian user myself, so resolving any problems Debian has with packages that I am involved with has a high priority for me.

You might want to hold out a few days until https://github.com/temisu/ancient/issues/37 is resolved before releasing an updated package for ancient, though.

**Comment by temisu** [comment] 2022-01-12 21:54
I replaced the version, made a new release- If it really was a version number mismatch, it should work now (at least in theory).

@alexmyczko can you retry?

**Comment by manxorist** [comment] 2022-01-13 06:52
> I replaced the version, made a new release- If it really was a version number mismatch, it should work now (at least in theory).

This issue almost certainly has nothing to do with the version mismatch.

I referenced the version mismatch issue here, because it may (although unlikely) turn out to cause even more trouble if the confused version would have ended up in a published debian package.

**Comment by alexmyczko** [comment] 2022-01-13 07:11
> I am really not an expert on (or have really any deeper knowledge at all about) debian packaging, but do you by any chance still have the file https://sources.debian.org/src/ancient/1.0-2/debian/install/ laying around in your updated debian packaging directory?

yes it was in the same browsable directory index as the linked build log...

> According to https://manpages.debian.org/testing/debhelper/dh_install.1.en.html it looks to me like it would, in addition to what make install installs, also install "ancient" from the current directory to"/usr/bin", which would overwrite the proper binary with whatever libtool had generated in the build directory.

that was exactly it! 1.0 had not installed the binary, so i added debian/install, but with 1.1/2.0 it's not needed anymore...
just rebuilt and installed:
```
Usage: ancient identify packed_input_file
 - identifies compression used in a file
Usage: ancient verify packed_input_file unpacked_comparison_file
 - verifies decompression against known good unpacked file
Usage: ancient decompress packed_input_file output_file
 - decompresses single file
Usage: ancient scan input_dir output_dir
 - scans input directory recursively and stores all found
 - known compressed streams to separate files in output directory
```

> I am a Debian user myself, so resolving any problems Debian has with packages that I am involved with has a high priority for me.
> 
> You might want to hold out a few days until #37 is resolved before releasing an updated package for ancient, though.

```
# dpkg -L ancient
/.
/usr
/usr/bin
/usr/bin/ancient
/usr/include
/usr/include/ancient
/usr/include/ancient/ancient.hpp
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libancient.a
/usr/lib/x86_64-linux-gnu/libancient.la
/usr/lib/x86_64-linux-gnu/libancient.so.2.0.0
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/libancient.pc
/usr/share
/usr/share/doc
/usr/share/doc/ancient
/usr/share/doc/ancient/LICENSE
/usr/share/doc/ancient/README.md.gz
/usr/share/doc/ancient/changelog.Debian.gz
/usr/share/doc/ancient/copyright
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/ancient.1.gz
/usr/lib/x86_64-linux-gnu/libancient.so
/usr/lib/x86_64-linux-gnu/libancient.so.2
```

this requires adding additional binary packages, splitting the package into libancientN and libancient-dev among the existing `ancient`...

do you want to pick up the manual page and improve it?

**Comment by manxorist** [comment] 2022-01-13 07:50
> this requires adding additional binary packages, splitting the package into libancientN and libancient-dev among the existing `ancient`...

I guess so, yes.

> do you want to pick up the manual page and improve it?

Ancient could either do that, or convert the output to the `ancient` binary to be compatible with help2man (https://www.gnu.org/software/help2man/) and use that to generate the man page (this is what I do for openmpt123 in libopenmpt).

The former has the advantage of working flawlessly with cross-compiling, the latter has the advantage of not duplicating the usage documentation.

@temisu what do you think?

**Comment by temisu** [comment] 2022-01-13 08:18
The help text is really terse, so help2man would not be that good. Letm me check the existing man page is something we could use as a base

**Comment by alexmyczko** [comment] 2022-01-13 08:51
offtopic: i've seen you're demoscener, and i either found you or the komposter software via you (or vice versa), did you see it entered debian as well? :)

**Comment by temisu** [comment] 2022-01-13 22:34
I installed debian & tools to try it myself, but unfortunately run into interesting set of issues.

If I use just the build files from the old one, I can produce a working .deb package - but it is still built with makefiles, no autoconfig there.

Since I'm still not an expert. Can you help me out here @alexmyczko Do you have your buildfiles somewhere I can try where this problem reproduces? But it looks like you got it already working. Now I'm just confused ...

Few other things
- I think I need to write a clean man-page - I do not want to mix the GPL stuff with non-GPL stuff. Usual problems will happen.
- komposter is not my project so I recommend asking electronoora about that. So far I do not know someone would have submitted it yet.
- As for the IRC, I'm not there but I can be found on some of the relevant discord servers

**Comment by manxorist** [comment] 2022-01-14 08:25
> I installed debian & tools to try it myself, but unfortunately run into interesting set of issues.
> 
> If I use just the build files from the old one, I can produce a working .deb package - but it is still built with makefiles, no autoconfig there.
> 
> Since I'm still not an expert. Can you help me out here @alexmyczko Do you have your buildfiles somewhere I can try where this problem reproduces? But it looks like you got it already working. Now I'm just confused ...

I do not think there ever was anything wrong with ancient in this regard. No need to try to reproduce anything. This was purely an issue on @alexmyczko 's side, and has already been confirmed so:
> that was exactly it!

**Comment by temisu** [comment] 2022-01-21 20:36
I'll put the task of creating better man-page in my long TODO-list. Meanwhile, it looks like packages can be created.

Re-open in case there are further issues

**Closed by temisu** 2022-01-21 20:36 UTC

**Comment by alexmyczko** [comment] 2022-08-21 18:17
sorry this took me so long, but finally 2.x made it into debian. however: https://buildd.debian.org/status/package.php?p=ancient&suite=sid

**Comment by manxorist** [comment] 2022-08-21 18:38
@alexmyczko can you please open a new issue for that?

I am looking at right now, but so far I am pretty confused.

A new open issue will help to not forget if I cannot fix it right away.

**Comment by alexmyczko** [comment] 2022-08-21 18:39
i will when i am sure it is not my fault, appears the binary upload amd64 was fine all others not let me check again. (that was quick, your answer)

**Comment by manxorist** [comment] 2022-08-21 18:50
I cannot reproduce the problem on Debian Testing (amd64). I did also verify that the variables that AC_SUBST should provide are correctly provided to the build.

**Comment by alexmyczko** [comment] 2022-08-21 18:52
appears to be missing build-depends: autoconf, testing and uploading after successfull test - sorry for the noise

**Comment by manxorist** [comment] 2022-08-21 18:55
It probably also needs autoconf-archive (for `AX_CXX_COMPILE_STDCXX`).

**Comment by alexmyczko** [comment] 2022-08-21 18:57
or one more more of: pkg-config m4 libtool
